--Question 2
drop sequence generateBuildingId;
create sequence generateBuildingId start with 9100;

--Question 3
CREATE OR REPLACE PROCEDURE ADDNEWBULDING(BUILDING_NAME IN VARCHAR2,BUILDING_LOCATION IN VARCHAR2, READY_TO_LEASE IN NUMBER)
IS
BEGIN
--INSERT INTO BUILDING VALUES(BUILDING_ID,BUILDING_NAME,BUILDING_LOCATION,READY_TO_LEASE);
INSERT INTO BUILDING VALUES(phyID_seq.nextval,BUILDING_NAME,BUILDING_LOCATION,READY_TO_LEASE);
END;
/

--Question 4

CREATE OR REPLACE PROCEDURE deleteLeaseHolder(LEASE_ID IN NUMBER)
IS
BEGIN
DELETE FROM LEASE_HOLDER WHERE LEASE_HOLDER_ID = LEASE_ID;
COMMIT;
END;
/